name:                implicit-hie
version:             0.1.0.0
github:              "Avi-D-coder/implicit-hie"
license:             BSD3
author:              "Avi Dessauer"
maintainer:          "avi.the.coder@gmail.com"
copyright:           "2020"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: "Auto generate a stack or cabal multi component hie.yaml file"

dependencies:
- base >= 4.7 && < 5
- text
- attoparsec
- yaml

ghc-options:
- -O2
- -flate-specialise
- -fexpose-all-unfoldings
- -fspecialize-aggressively
- -Wall
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -fno-warn-unused-imports
- -fno-warn-unused-binds
- -fno-warn-name-shadowing
- -fwarn-redundant-constraints

library:
  source-dirs: src

executables:
  gen-hie:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - implicit-hie
    - directory
    - filepath

tests:
  implicit-hie-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - implicit-hie
    - hspec
    - hspec-attoparsec
